/*
 Navicat Premium Data Transfer

 Source Server         : uppicsys
 Source Server Type    : MySQL
 Source Server Version : 80022
 Source Host           : localhost:3306
 Source Schema         : exam

 Target Server Type    : MySQL
 Target Server Version : 80022
 File Encoding         : 65001

 Date: 03/03/2021 22:08:14
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for exam_2
-- ----------------------------
DROP TABLE IF EXISTS `exam_2`;
CREATE TABLE `exam_2`  (
  `students_num` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `flag` int NOT NULL DEFAULT 0,
  `t1` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '考生作答',
  `t2` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t3` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t4` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t5` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t6` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t7` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t8` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t9` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t10` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t11` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t12` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t13` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t14` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t15` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t16` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t17` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t18` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t19` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t20` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t21` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t22` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t23` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t24` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t25` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t26` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t27` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t28` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t29` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t30` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t31` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t32` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t33` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t34` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t35` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t36` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t37` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t38` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t39` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t40` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t41` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t42` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t43` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t44` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t45` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t46` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t47` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t48` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t49` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t50` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `s1` int NOT NULL DEFAULT 0 COMMENT '考生得分',
  `s2` int NOT NULL DEFAULT 0,
  `s3` int NOT NULL DEFAULT 0,
  `s4` int NOT NULL DEFAULT 0,
  `s5` int NOT NULL DEFAULT 0,
  `s6` int NOT NULL DEFAULT 0,
  `s7` int NOT NULL DEFAULT 0,
  `s8` int NOT NULL DEFAULT 0,
  `s9` int NOT NULL DEFAULT 0,
  `s10` int NOT NULL DEFAULT 0,
  `s11` int NOT NULL DEFAULT 0,
  `s12` int NOT NULL DEFAULT 0,
  `s13` int NOT NULL DEFAULT 0,
  `s14` int NOT NULL DEFAULT 0,
  `s15` int NOT NULL DEFAULT 0,
  `s16` int NOT NULL DEFAULT 0,
  `s17` int NOT NULL DEFAULT 0,
  `s18` int NOT NULL DEFAULT 0,
  `s19` int NOT NULL DEFAULT 0,
  `s20` int NOT NULL DEFAULT 0,
  `s21` int NOT NULL DEFAULT 0,
  `s22` int NOT NULL DEFAULT 0,
  `s23` int NOT NULL DEFAULT 0,
  `s24` int NOT NULL DEFAULT 0,
  `s25` int NOT NULL DEFAULT 0,
  `s26` int NOT NULL DEFAULT 0,
  `s27` int NOT NULL DEFAULT 0,
  `s28` int NOT NULL DEFAULT 0,
  `s29` int NOT NULL DEFAULT 0,
  `s30` int NOT NULL DEFAULT 0,
  `s31` int NOT NULL DEFAULT 0,
  `s32` int NOT NULL DEFAULT 0,
  `s33` int NOT NULL DEFAULT 0,
  `s34` int NOT NULL DEFAULT 0,
  `s35` int NOT NULL DEFAULT 0,
  `s36` int NOT NULL DEFAULT 0,
  `s37` int NOT NULL DEFAULT 0,
  `s38` int NOT NULL DEFAULT 0,
  `s39` int NOT NULL DEFAULT 0,
  `s40` int NOT NULL DEFAULT 0,
  `s41` int NOT NULL DEFAULT 0,
  `s42` int NOT NULL DEFAULT 0,
  `s43` int NOT NULL DEFAULT 0,
  `s44` int NOT NULL DEFAULT 0,
  `s45` int NULL DEFAULT 0,
  `s46` int NOT NULL DEFAULT 0,
  `s47` int NOT NULL DEFAULT 0,
  `s48` int NOT NULL DEFAULT 0,
  `s49` int NULL DEFAULT 0,
  `s50` int NOT NULL DEFAULT 0,
  `score_1` int NOT NULL DEFAULT 0 COMMENT '客观题总分',
  `score_2` int NOT NULL DEFAULT 0 COMMENT '主观题总分',
  `score` int NOT NULL DEFAULT 0 COMMENT '得分',
  `scoreRank` int NOT NULL DEFAULT 0 COMMENT '名次',
  PRIMARY KEY (`students_num`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of exam_2
-- ----------------------------
INSERT INTO `exam_2` VALUES ('201943010119', 1, 'A', 'B', 'C', 'D', 'B', '因为我最喜欢PHP!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 10, 30, 20, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 40, 70, 1);

-- ----------------------------
-- Table structure for exam_3
-- ----------------------------
DROP TABLE IF EXISTS `exam_3`;
CREATE TABLE `exam_3`  (
  `students_num` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `flag` int NOT NULL DEFAULT 0,
  `t1` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '考生作答',
  `t2` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t3` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t4` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t5` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t6` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t7` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t8` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t9` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t10` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t11` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t12` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t13` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t14` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t15` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t16` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t17` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t18` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t19` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t20` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t21` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t22` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t23` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t24` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t25` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t26` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t27` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t28` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t29` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t30` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t31` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t32` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t33` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t34` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t35` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t36` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t37` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t38` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t39` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t40` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t41` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t42` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t43` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t44` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t45` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t46` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t47` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t48` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t49` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t50` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `s1` int NOT NULL DEFAULT 0 COMMENT '考生得分',
  `s2` int NOT NULL DEFAULT 0,
  `s3` int NOT NULL DEFAULT 0,
  `s4` int NOT NULL DEFAULT 0,
  `s5` int NOT NULL DEFAULT 0,
  `s6` int NOT NULL DEFAULT 0,
  `s7` int NOT NULL DEFAULT 0,
  `s8` int NOT NULL DEFAULT 0,
  `s9` int NOT NULL DEFAULT 0,
  `s10` int NOT NULL DEFAULT 0,
  `s11` int NOT NULL DEFAULT 0,
  `s12` int NOT NULL DEFAULT 0,
  `s13` int NOT NULL DEFAULT 0,
  `s14` int NOT NULL DEFAULT 0,
  `s15` int NOT NULL DEFAULT 0,
  `s16` int NOT NULL DEFAULT 0,
  `s17` int NOT NULL DEFAULT 0,
  `s18` int NOT NULL DEFAULT 0,
  `s19` int NOT NULL DEFAULT 0,
  `s20` int NOT NULL DEFAULT 0,
  `s21` int NOT NULL DEFAULT 0,
  `s22` int NOT NULL DEFAULT 0,
  `s23` int NOT NULL DEFAULT 0,
  `s24` int NOT NULL DEFAULT 0,
  `s25` int NOT NULL DEFAULT 0,
  `s26` int NOT NULL DEFAULT 0,
  `s27` int NOT NULL DEFAULT 0,
  `s28` int NOT NULL DEFAULT 0,
  `s29` int NOT NULL DEFAULT 0,
  `s30` int NOT NULL DEFAULT 0,
  `s31` int NOT NULL DEFAULT 0,
  `s32` int NOT NULL DEFAULT 0,
  `s33` int NOT NULL DEFAULT 0,
  `s34` int NOT NULL DEFAULT 0,
  `s35` int NOT NULL DEFAULT 0,
  `s36` int NOT NULL DEFAULT 0,
  `s37` int NOT NULL DEFAULT 0,
  `s38` int NOT NULL DEFAULT 0,
  `s39` int NOT NULL DEFAULT 0,
  `s40` int NOT NULL DEFAULT 0,
  `s41` int NOT NULL DEFAULT 0,
  `s42` int NOT NULL DEFAULT 0,
  `s43` int NOT NULL DEFAULT 0,
  `s44` int NOT NULL DEFAULT 0,
  `s45` int NULL DEFAULT 0,
  `s46` int NOT NULL DEFAULT 0,
  `s47` int NOT NULL DEFAULT 0,
  `s48` int NOT NULL DEFAULT 0,
  `s49` int NULL DEFAULT 0,
  `s50` int NOT NULL DEFAULT 0,
  `score_1` int NOT NULL DEFAULT 0 COMMENT '客观题总分',
  `score_2` int NOT NULL DEFAULT 0 COMMENT '主观题总分',
  `score` int NOT NULL DEFAULT 0 COMMENT '得分',
  `scoreRank` int NOT NULL DEFAULT 0 COMMENT '名次',
  PRIMARY KEY (`students_num`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of exam_3
-- ----------------------------
INSERT INTO `exam_3` VALUES ('201943010119', 1, 'B', 'paper', 'NO WHY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 60, 40, 40, 42);

-- ----------------------------
-- Table structure for exam_4
-- ----------------------------
DROP TABLE IF EXISTS `exam_4`;
CREATE TABLE `exam_4`  (
  `students_num` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `flag` int NOT NULL DEFAULT 0,
  `t1` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '考生作答',
  `t2` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t3` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t4` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t5` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t6` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t7` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t8` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t9` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t10` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t11` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t12` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t13` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t14` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t15` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t16` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t17` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t18` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t19` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t20` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t21` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t22` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t23` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t24` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t25` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t26` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t27` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t28` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t29` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t30` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t31` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t32` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t33` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t34` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t35` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t36` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t37` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t38` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t39` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t40` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t41` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t42` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t43` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t44` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t45` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t46` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t47` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t48` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t49` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t50` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `s1` int NOT NULL DEFAULT 0 COMMENT '考生得分',
  `s2` int NOT NULL DEFAULT 0,
  `s3` int NOT NULL DEFAULT 0,
  `s4` int NOT NULL DEFAULT 0,
  `s5` int NOT NULL DEFAULT 0,
  `s6` int NOT NULL DEFAULT 0,
  `s7` int NOT NULL DEFAULT 0,
  `s8` int NOT NULL DEFAULT 0,
  `s9` int NOT NULL DEFAULT 0,
  `s10` int NOT NULL DEFAULT 0,
  `s11` int NOT NULL DEFAULT 0,
  `s12` int NOT NULL DEFAULT 0,
  `s13` int NOT NULL DEFAULT 0,
  `s14` int NOT NULL DEFAULT 0,
  `s15` int NOT NULL DEFAULT 0,
  `s16` int NOT NULL DEFAULT 0,
  `s17` int NOT NULL DEFAULT 0,
  `s18` int NOT NULL DEFAULT 0,
  `s19` int NOT NULL DEFAULT 0,
  `s20` int NOT NULL DEFAULT 0,
  `s21` int NOT NULL DEFAULT 0,
  `s22` int NOT NULL DEFAULT 0,
  `s23` int NOT NULL DEFAULT 0,
  `s24` int NOT NULL DEFAULT 0,
  `s25` int NOT NULL DEFAULT 0,
  `s26` int NOT NULL DEFAULT 0,
  `s27` int NOT NULL DEFAULT 0,
  `s28` int NOT NULL DEFAULT 0,
  `s29` int NOT NULL DEFAULT 0,
  `s30` int NOT NULL DEFAULT 0,
  `s31` int NOT NULL DEFAULT 0,
  `s32` int NOT NULL DEFAULT 0,
  `s33` int NOT NULL DEFAULT 0,
  `s34` int NOT NULL DEFAULT 0,
  `s35` int NOT NULL DEFAULT 0,
  `s36` int NOT NULL DEFAULT 0,
  `s37` int NOT NULL DEFAULT 0,
  `s38` int NOT NULL DEFAULT 0,
  `s39` int NOT NULL DEFAULT 0,
  `s40` int NOT NULL DEFAULT 0,
  `s41` int NOT NULL DEFAULT 0,
  `s42` int NOT NULL DEFAULT 0,
  `s43` int NOT NULL DEFAULT 0,
  `s44` int NOT NULL DEFAULT 0,
  `s45` int NULL DEFAULT 0,
  `s46` int NOT NULL DEFAULT 0,
  `s47` int NOT NULL DEFAULT 0,
  `s48` int NOT NULL DEFAULT 0,
  `s49` int NULL DEFAULT 0,
  `s50` int NOT NULL DEFAULT 0,
  `score_1` int NOT NULL DEFAULT 0 COMMENT '客观题总分',
  `score_2` int NOT NULL DEFAULT 0 COMMENT '主观题总分',
  `score` int NOT NULL DEFAULT 0 COMMENT '得分',
  `scoreRank` int NOT NULL DEFAULT 0 COMMENT '名次',
  PRIMARY KEY (`students_num`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of exam_4
-- ----------------------------
INSERT INTO `exam_4` VALUES ('201943010119', 1, 'D', 'paper', '就是牛', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 50, 80, 15);
INSERT INTO `exam_4` VALUES ('201943010114', 1, 'B', 'paper', '不知道', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 50, 100, 1);

-- ----------------------------
-- Table structure for exam_5
-- ----------------------------
DROP TABLE IF EXISTS `exam_5`;
CREATE TABLE `exam_5`  (
  `students_num` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `flag` int NOT NULL DEFAULT 0,
  `t1` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '考生作答',
  `t2` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t3` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t4` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t5` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t6` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t7` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t8` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t9` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t10` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t11` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t12` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t13` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t14` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t15` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t16` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t17` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t18` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t19` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t20` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t21` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t22` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t23` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t24` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t25` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t26` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t27` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t28` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t29` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t30` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t31` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t32` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t33` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t34` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t35` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t36` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t37` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t38` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t39` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t40` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t41` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t42` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t43` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t44` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t45` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t46` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t47` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t48` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t49` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t50` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `s1` int NOT NULL DEFAULT 0 COMMENT '考生得分',
  `s2` int NOT NULL DEFAULT 0,
  `s3` int NOT NULL DEFAULT 0,
  `s4` int NOT NULL DEFAULT 0,
  `s5` int NOT NULL DEFAULT 0,
  `s6` int NOT NULL DEFAULT 0,
  `s7` int NOT NULL DEFAULT 0,
  `s8` int NOT NULL DEFAULT 0,
  `s9` int NOT NULL DEFAULT 0,
  `s10` int NOT NULL DEFAULT 0,
  `s11` int NOT NULL DEFAULT 0,
  `s12` int NOT NULL DEFAULT 0,
  `s13` int NOT NULL DEFAULT 0,
  `s14` int NOT NULL DEFAULT 0,
  `s15` int NOT NULL DEFAULT 0,
  `s16` int NOT NULL DEFAULT 0,
  `s17` int NOT NULL DEFAULT 0,
  `s18` int NOT NULL DEFAULT 0,
  `s19` int NOT NULL DEFAULT 0,
  `s20` int NOT NULL DEFAULT 0,
  `s21` int NOT NULL DEFAULT 0,
  `s22` int NOT NULL DEFAULT 0,
  `s23` int NOT NULL DEFAULT 0,
  `s24` int NOT NULL DEFAULT 0,
  `s25` int NOT NULL DEFAULT 0,
  `s26` int NOT NULL DEFAULT 0,
  `s27` int NOT NULL DEFAULT 0,
  `s28` int NOT NULL DEFAULT 0,
  `s29` int NOT NULL DEFAULT 0,
  `s30` int NOT NULL DEFAULT 0,
  `s31` int NOT NULL DEFAULT 0,
  `s32` int NOT NULL DEFAULT 0,
  `s33` int NOT NULL DEFAULT 0,
  `s34` int NOT NULL DEFAULT 0,
  `s35` int NOT NULL DEFAULT 0,
  `s36` int NOT NULL DEFAULT 0,
  `s37` int NOT NULL DEFAULT 0,
  `s38` int NOT NULL DEFAULT 0,
  `s39` int NOT NULL DEFAULT 0,
  `s40` int NOT NULL DEFAULT 0,
  `s41` int NOT NULL DEFAULT 0,
  `s42` int NOT NULL DEFAULT 0,
  `s43` int NOT NULL DEFAULT 0,
  `s44` int NOT NULL DEFAULT 0,
  `s45` int NULL DEFAULT 0,
  `s46` int NOT NULL DEFAULT 0,
  `s47` int NOT NULL DEFAULT 0,
  `s48` int NOT NULL DEFAULT 0,
  `s49` int NULL DEFAULT 0,
  `s50` int NOT NULL DEFAULT 0,
  `score_1` int NOT NULL DEFAULT 0 COMMENT '客观题总分',
  `score_2` int NOT NULL DEFAULT 0 COMMENT '主观题总分',
  `score` int NOT NULL DEFAULT 0 COMMENT '得分',
  `scoreRank` int NOT NULL DEFAULT 0 COMMENT '名次',
  PRIMARY KEY (`students_num`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of exam_5
-- ----------------------------
INSERT INTO `exam_5` VALUES ('201943010119', 1, 'D', 'D', '好', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 30, 55, 2);
INSERT INTO `exam_5` VALUES ('201943010114', 1, 'B', 'D', '好\r\n', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 50, 100, 1);

-- ----------------------------
-- Table structure for exam_8
-- ----------------------------
DROP TABLE IF EXISTS `exam_8`;
CREATE TABLE `exam_8`  (
  `students_num` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `flag` int NOT NULL DEFAULT 0,
  `t1` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '考生作答',
  `t2` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t3` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t4` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t5` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t6` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t7` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t8` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t9` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t10` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t11` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t12` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t13` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t14` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t15` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t16` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t17` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t18` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t19` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t20` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t21` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t22` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t23` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t24` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t25` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t26` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t27` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t28` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t29` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t30` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t31` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t32` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t33` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t34` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t35` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t36` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t37` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t38` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t39` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t40` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t41` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t42` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t43` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t44` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t45` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t46` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t47` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t48` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t49` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `t50` varchar(110) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `s1` int NOT NULL DEFAULT 0 COMMENT '考生得分',
  `s2` int NOT NULL DEFAULT 0,
  `s3` int NOT NULL DEFAULT 0,
  `s4` int NOT NULL DEFAULT 0,
  `s5` int NOT NULL DEFAULT 0,
  `s6` int NOT NULL DEFAULT 0,
  `s7` int NOT NULL DEFAULT 0,
  `s8` int NOT NULL DEFAULT 0,
  `s9` int NOT NULL DEFAULT 0,
  `s10` int NOT NULL DEFAULT 0,
  `s11` int NOT NULL DEFAULT 0,
  `s12` int NOT NULL DEFAULT 0,
  `s13` int NOT NULL DEFAULT 0,
  `s14` int NOT NULL DEFAULT 0,
  `s15` int NOT NULL DEFAULT 0,
  `s16` int NOT NULL DEFAULT 0,
  `s17` int NOT NULL DEFAULT 0,
  `s18` int NOT NULL DEFAULT 0,
  `s19` int NOT NULL DEFAULT 0,
  `s20` int NOT NULL DEFAULT 0,
  `s21` int NOT NULL DEFAULT 0,
  `s22` int NOT NULL DEFAULT 0,
  `s23` int NOT NULL DEFAULT 0,
  `s24` int NOT NULL DEFAULT 0,
  `s25` int NOT NULL DEFAULT 0,
  `s26` int NOT NULL DEFAULT 0,
  `s27` int NOT NULL DEFAULT 0,
  `s28` int NOT NULL DEFAULT 0,
  `s29` int NOT NULL DEFAULT 0,
  `s30` int NOT NULL DEFAULT 0,
  `s31` int NOT NULL DEFAULT 0,
  `s32` int NOT NULL DEFAULT 0,
  `s33` int NOT NULL DEFAULT 0,
  `s34` int NOT NULL DEFAULT 0,
  `s35` int NOT NULL DEFAULT 0,
  `s36` int NOT NULL DEFAULT 0,
  `s37` int NOT NULL DEFAULT 0,
  `s38` int NOT NULL DEFAULT 0,
  `s39` int NOT NULL DEFAULT 0,
  `s40` int NOT NULL DEFAULT 0,
  `s41` int NOT NULL DEFAULT 0,
  `s42` int NOT NULL DEFAULT 0,
  `s43` int NOT NULL DEFAULT 0,
  `s44` int NOT NULL DEFAULT 0,
  `s45` int NULL DEFAULT 0,
  `s46` int NOT NULL DEFAULT 0,
  `s47` int NOT NULL DEFAULT 0,
  `s48` int NOT NULL DEFAULT 0,
  `s49` int NULL DEFAULT 0,
  `s50` int NOT NULL DEFAULT 0,
  `score_1` int NOT NULL DEFAULT 0 COMMENT '客观题总分',
  `score_2` int NOT NULL DEFAULT 0 COMMENT '主观题总分',
  `score` int NOT NULL DEFAULT 0 COMMENT '得分',
  `scoreRank` int NOT NULL DEFAULT 0 COMMENT '名次',
  PRIMARY KEY (`students_num`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of exam_8
-- ----------------------------
INSERT INTO `exam_8` VALUES ('201943010119', 1, 'B', '123', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 70, 100, 1);

-- ----------------------------
-- Table structure for exam_history
-- ----------------------------
DROP TABLE IF EXISTS `exam_history`;
CREATE TABLE `exam_history`  (
  `num` int NOT NULL AUTO_INCREMENT,
  `paper_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `flag` int NULL DEFAULT NULL,
  `time_start` timestamp(0) NULL DEFAULT NULL,
  `duration` timestamp(0) NULL DEFAULT NULL,
  `number` int NULL DEFAULT NULL,
  `t1` int NULL DEFAULT NULL,
  `t2` int NULL DEFAULT NULL,
  `t3` int NULL DEFAULT NULL,
  `t4` int NULL DEFAULT NULL,
  `t5` int NULL DEFAULT NULL,
  `t6` int NULL DEFAULT NULL,
  `t7` int NULL DEFAULT NULL,
  `t8` int NULL DEFAULT NULL,
  `t9` int NULL DEFAULT NULL,
  `t10` int NULL DEFAULT NULL,
  `t11` int NULL DEFAULT NULL,
  `t12` int NULL DEFAULT NULL,
  `t13` int NULL DEFAULT NULL,
  `t14` int NULL DEFAULT NULL,
  `t15` int NULL DEFAULT NULL,
  `t16` int NULL DEFAULT NULL,
  `t17` int NULL DEFAULT NULL,
  `t18` int NULL DEFAULT NULL,
  `t19` int NULL DEFAULT NULL,
  `t20` int NULL DEFAULT NULL,
  `t21` int NULL DEFAULT NULL,
  `t22` int NULL DEFAULT NULL,
  `t23` int NULL DEFAULT NULL,
  `t24` int NULL DEFAULT NULL,
  `t25` int NULL DEFAULT NULL,
  `t26` int NULL DEFAULT NULL,
  `t27` int NULL DEFAULT NULL,
  `t28` int NULL DEFAULT NULL,
  `t29` int NULL DEFAULT NULL,
  `t30` int NULL DEFAULT NULL,
  `t31` int NULL DEFAULT NULL,
  `t32` int NULL DEFAULT NULL,
  `t33` int NULL DEFAULT NULL,
  `t34` int NULL DEFAULT NULL,
  `t35` int NULL DEFAULT NULL,
  `t36` int NULL DEFAULT NULL,
  `t37` int NULL DEFAULT NULL,
  `t38` int NULL DEFAULT NULL,
  `t39` int NULL DEFAULT NULL,
  `t40` int NULL DEFAULT NULL,
  `t41` int NULL DEFAULT NULL,
  `t42` int NULL DEFAULT NULL,
  `t43` int NULL DEFAULT NULL,
  `t44` int NULL DEFAULT NULL,
  `t45` int NULL DEFAULT NULL,
  `t46` int NULL DEFAULT NULL,
  `t47` int NULL DEFAULT NULL,
  `t48` int NULL DEFAULT NULL,
  `t49` int NULL DEFAULT NULL,
  `t50` int NULL DEFAULT NULL,
  `s1` int NULL DEFAULT NULL,
  `s2` int NULL DEFAULT NULL,
  `s3` int NULL DEFAULT NULL,
  `s4` int NULL DEFAULT NULL,
  `s5` int NULL DEFAULT NULL,
  `s6` int NULL DEFAULT NULL,
  `s7` int NULL DEFAULT NULL,
  `s8` int NULL DEFAULT NULL,
  `s9` int NULL DEFAULT NULL,
  `s10` int NULL DEFAULT NULL,
  `s11` int NULL DEFAULT NULL,
  `s12` int NULL DEFAULT NULL,
  `s13` int NULL DEFAULT NULL,
  `s14` int NULL DEFAULT NULL,
  `s15` int NULL DEFAULT NULL,
  `s16` int NULL DEFAULT NULL,
  `s17` int NULL DEFAULT NULL,
  `s18` int NULL DEFAULT NULL,
  `s19` int NULL DEFAULT NULL,
  `s20` int NULL DEFAULT NULL,
  `s21` int NULL DEFAULT NULL,
  `s22` int NULL DEFAULT NULL,
  `s23` int NULL DEFAULT NULL,
  `s24` int NULL DEFAULT NULL,
  `s25` int NULL DEFAULT NULL,
  `s26` int NULL DEFAULT NULL,
  `s27` int NULL DEFAULT NULL,
  `s28` int NULL DEFAULT NULL,
  `s29` int NULL DEFAULT NULL,
  `s30` int NULL DEFAULT NULL,
  `s31` int NULL DEFAULT NULL,
  `s32` int NULL DEFAULT NULL,
  `s33` int NULL DEFAULT NULL,
  `s34` int NULL DEFAULT NULL,
  `s35` int NULL DEFAULT NULL,
  `s36` int NULL DEFAULT NULL,
  `s37` int NULL DEFAULT NULL,
  `s38` int NULL DEFAULT NULL,
  `s39` int NULL DEFAULT NULL,
  `s40` int NULL DEFAULT NULL,
  `s41` int NULL DEFAULT NULL,
  `s42` int NULL DEFAULT NULL,
  `s43` int NULL DEFAULT NULL,
  `s44` int NULL DEFAULT NULL,
  `s45` int NULL DEFAULT NULL,
  `s46` int NULL DEFAULT NULL,
  `s47` int NULL DEFAULT NULL,
  `s48` int NULL DEFAULT NULL,
  `s49` int NULL DEFAULT NULL,
  `s50` int NULL DEFAULT NULL,
  PRIMARY KEY (`num`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 8 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of exam_history
-- ----------------------------
INSERT INTO `exam_history` VALUES (2, '2020-2021秋季学期PHP程序设计期末检测', 1, '2020-12-08 20:00:00', '2020-12-27 22:00:00', 6, 7, 2, 6, 4, 5, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 20, 30, 20, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `exam_history` VALUES (3, 'PHP程序设计第2次阶段检测', 1, '2020-12-10 13:36:00', '2020-12-10 13:40:00', 3, 2, 3, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 35, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `exam_history` VALUES (4, 'PHP程序设计第3次阶段检测', 1, '2020-12-13 17:44:00', '2020-12-13 19:44:00', 3, 4, 3, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 30, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `exam_history` VALUES (5, 'PHP程序设计第4次阶段检测', 1, '2020-12-13 17:45:00', '2020-12-13 19:45:00', 3, 9, 10, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 25, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `exam_history` VALUES (8, 'PHP程序设计第6次阶段检测', 1, '2020-12-14 10:21:00', '2020-12-14 12:21:00', 2, 9, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

-- ----------------------------
-- Table structure for problems
-- ----------------------------
DROP TABLE IF EXISTS `problems`;
CREATE TABLE `problems`  (
  `num` int NOT NULL AUTO_INCREMENT,
  `type` int NULL DEFAULT NULL,
  `A` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `B` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `C` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `D` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ans` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `exp` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `item` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`num`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 12 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of problems
-- ----------------------------
INSERT INTO `problems` VALUES (2, 1, '1', '2', '3', '4', 'B', '因为一加一等于2', '请问 1 + 1 = ？');
INSERT INTO `problems` VALUES (3, 2, NULL, NULL, NULL, NULL, 'paper', '因为所以，科学道理！', '试卷的英文单词是什么？');
INSERT INTO `problems` VALUES (4, 1, '5', '10', '15', '20', 'B', '因为5加5等于10', '请问 5 + 5 = ？');
INSERT INTO `problems` VALUES (5, 1, '2', '4', '6', '8', 'B', '因为2加2等于4', '请问 2 + 2 = ？');
INSERT INTO `problems` VALUES (6, 1, '3', '6', '9', '12', 'B', '因为3加3等于6', '请问 3 + 3 = ？');
INSERT INTO `problems` VALUES (7, 1, '4', '8', '12', '16', 'B', '因为4加4等于8', '请问 4 + 4 = ？');
INSERT INTO `problems` VALUES (8, 3, NULL, NULL, NULL, NULL, 'PHP is the best language for web programming', '因为出自官方文档第一句话“PHP is the best language for web programming,but what about other languages?', '为什么PHP是世界上最好的语言？');
INSERT INTO `problems` VALUES (9, 1, '$_post[\"名称\"] ', '$_POST[\"名称\"]', '$post[\"名称\"]', '$POST[\"名称\"]', 'B', '死记硬背', '读取post方法传递的表单元素值的方法是:');
INSERT INTO `problems` VALUES (10, 1, 'Print( )', 'print( )', 'Print_r()', 'print_r()', 'D', '死记硬背', '要查看一个结构类型变量的值,可以使用函数( )');
INSERT INTO `problems` VALUES (11, 1, '$_COOKIE', '$_COOKIES', '$_GETCOOKIE', '$_GETCOOKIES', 'A', '死记硬背', '在PHP中哪个变量数组总是包含所有总客户端发出的cookies数据(    )');

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`  (
  `username` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `pwd` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `realname` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `collage` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `profession` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `kind` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES ('201943010114', '123', '贾金融', '财经学院', '假会计', '3');
INSERT INTO `user` VALUES ('201943010119', '123', '莫远征', '智能装备学院', '计算机科学与技术', '3');
INSERT INTO `user` VALUES ('201943010199', '123', 'Harry Potter', '格兰芬多学院', '魔法', '3');
INSERT INTO `user` VALUES ('admin', 'admin', '沈腾', '教务处', '学籍管理员', '1');
INSERT INTO `user` VALUES ('kongzi', '123', '孔老二', '文学院', '教授', '2');

SET FOREIGN_KEY_CHECKS = 1;
